# Generated by Django 5.1.6 on 2025-03-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_shorturl_current_url_shorturl_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='short_code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
